[package]
name = "raidz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
colored = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabled = { version = "0.16", features = ["ansi"] }
